<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>farah</AssemblyName>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RootNamespace>DockerFarah</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Farah.Tests" />
    </ItemGroup>
</Project>
