PassEnv SERVER_NAME
ServerName ${SERVER_NAME}

DirectoryIndex index.php index.xhtml index.html index.svg

Alias /farah.php /farah/index.php
FallbackResource /farah.php

<Directory /farah>
    Require all granted
</Directory>
