name: Docker

on:
    push:
        branches:
            - "main"
        paths:
            - "linux/**"
            - "windows/**"
            - ".github/workflows/docker.yml"
    workflow_dispatch:
    schedule:
        - cron: "0 0 1 * *"

permissions:
    contents: read

concurrency:
    group: docker-publish
    cancel-in-progress: false

jobs:
    publish:
        strategy:
            fail-fast: false
            matrix:
                variant:
                    - tag: "8.2"
                      build_args:
                          PHP_VERSION: "8.2"
                          DEBIAN: bookworm
                    - tag: "8.3"
                      build_args:
                          PHP_VERSION: "8.3"
                          DEBIAN: bookworm
                    - tag: "8.4"
                      build_args:
                          PHP_VERSION: "8.4"
                          DEBIAN: bookworm
                    - tag: "8.5"
                      build_args:
                          PHP_VERSION: "8.5"
                          DEBIAN: bookworm

        uses: Faulo/workflows-docker/.github/workflows/publish.yml@v1
        with:
            image: farah
            tag: ${{matrix.variant.tag}}
            build_args: ${{toJSON(matrix.variant.build_args)}}
        secrets:
            DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
