name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]
        os: ["windows"]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}}
        working-directory: .
        run: docker build --isolation=hyperv ${{matrix.os}} -t ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}} --build-arg PHP_VERSION=${{matrix.php}}
      - 
        name: Push ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}}
        run: docker image push ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}}
  docker-linux:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]
        os: ["linux"]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-${{matrix.os}}
          platforms: ${{matrix.os}}/amd64
          context: "{{defaultContext}}:${{matrix.os}}"
          file: Dockerfile
          build-args: PHP_VERSION=${{matrix.php}}
          provenance: false
  merge:
    runs-on: ubuntu-24.04
    needs:
    - docker-windows
    - docker-linux
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Merge manifests
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-linux, ${{secrets.DOCKERHUB_USERNAME}}/farah:${{matrix.php}}-windows
          push: true
