name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]
        os: ["linux", "windows"]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push farah
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faulo/farah:${{matrix.php}}
          platforms: ${{ matrix.os }}/amd64
          context: "{{ defaultContext }}:${{ matrix.os  }}"
          file: Dockerfile
          build-args: PHP_VERSION=${{matrix.php}}
